; PlatformIO Project Configuration File
;
<<<<<<< HEAD
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
=======
;Projekt Spion Display Teil.
;aktuelle Version 1.0.1 
; 26.11.2026 before 8:00 merge to master
; Version now 1.1.0

>
>>>>>> eeeb1d9 (26.11.2025 after merge to master some comments)

[platformio]
src_dir = src
boards_dir = .

[env:esp32-s3-devkitc-1-myboard]
platform = espressif32
board = esp32-s3-devkitc-1-myboard
framework = arduino
platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32#2.0.3
build_flags = 
	-D LV_LVGL_H_INCLUDE_SIMPLE
	-I./include
	-DBOARD_HAS_PSRAN
lib_deps = 
	lovyan03/LovyanGFX@^1.1.12
	tamctec/TAMC_GT911@^1.0.2
	gilmaimon/ArduinoWebsockets@^0.5.4
	lvgl/lvgl@8.3.6
board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_speed = 460800
upload_port = /dev/cu.usbserial-14640
monitor_port = /dev/cu.usbserial-14640